graph TD
    tools[tools - 8 bookmarks]
    ai_ml[ai_ml - 69 bookmarks]
    general[general - 16 bookmarks]
    programming[programming - 6 bookmarks]
    devops[devops - 1 bookmarks]
    tools --> ai_ml
    ai_ml --> programming